[xdebug]
zend_extension=xdebug
; Set XDEBUG_MODE=debug in compose.yml to enable. Defaults to off.
xdebug.mode=off
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log
