<?php
/**
 * Output favicon and PWA icon meta tags in <head>.
 *
 * Place the icon files generated by https://realfavicongenerator.net
 * into theme_components/icons/ so they are copied to assets/icons/ on build.
 *
 * @link https://realfavicongenerator.net
 *
 * @package core_wp
 */

if ( ! function_exists( 'core_wp_site_icons' ) ) {
	/**
	 * Output favicon and PWA icon meta tags in <head>.
	 */
	function core_wp_site_icons() {
		$icons_uri = get_template_directory_uri() . '/assets/icons';
		$site_name = esc_attr( get_bloginfo( 'name' ) );

		$tags  = '<link rel="apple-touch-icon" sizes="180x180" href="' . esc_url( $icons_uri . '/apple-touch-icon.png' ) . '">' . "\n";
		$tags .= '<link rel="icon" type="image/png" sizes="32x32" href="' . esc_url( $icons_uri . '/favicon-32x32.png' ) . '">' . "\n";
		$tags .= '<link rel="icon" type="image/png" sizes="16x16" href="' . esc_url( $icons_uri . '/favicon-16x16.png' ) . '">' . "\n";
		$tags .= '<link rel="manifest" href="' . esc_url( $icons_uri . '/site.webmanifest' ) . '">' . "\n";
		$tags .= '<link rel="mask-icon" href="' . esc_url( $icons_uri . '/safari-pinned-tab.svg' ) . '" color="#5bbad5">' . "\n";
		$tags .= '<link rel="shortcut icon" href="' . esc_url( $icons_uri . '/favicon.ico' ) . '">' . "\n";
		$tags .= '<meta name="msapplication-TileColor" content="#232c97">' . "\n";
		$tags .= '<meta name="msapplication-config" content="' . esc_url( $icons_uri . '/browserconfig.xml' ) . '">' . "\n";
		$tags .= '<meta name="theme-color" content="#ffffff">' . "\n";
		$tags .= '<meta name="apple-mobile-web-app-title" content="' . $site_name . '">' . "\n";
		$tags .= '<meta name="application-name" content="' . $site_name . '">' . "\n";

		echo $tags; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}
}
add_action( 'wp_head', 'core_wp_site_icons', 1 );
